sudo: false
language: node_js
node_js: 6
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - pushd local_modules/yp
  - npm run debug-build
  - node .& npm test; kill $!
  - popd
