sudo: false
language: node_js
node_js: 6
addons:
  firefox: "51.0.1"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pushd local_modules/p2pcommunication && npm install && popd
  - pushd local_modules/p2pcommunication-client && npm install && popd
  - pushd local_modules/p2pdatasharing && npm install && popd
  - pushd local_modules/p2pdatasharing-client && npm install && popd
before_script:
  - pushd local_modules/p2pcommunication && npm run build && popd
  - pushd local_modules/p2pcommunication-client && npm run build && popd
  - pushd local_modules/p2pdatasharing && npm run build && popd
  - pushd local_modules/p2pdatasharing-client && npm run build && popd
script:
  - pushd local_modules/p2pcommunication
  - node lib/server.js&
  - popd
  - pushd local_modules/p2pcommunication-client
  - npm test
  - popd
  - kill $!
  - pushd local_modules/p2pdatasharing
  - node lib/server.js&
  - popd
  - pushd local_modules/p2pdatasharing-client
  - npm test
  - popd
  - kill $!
