sudo: false
language: node_js
node_js: 6
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - cd local_modules/p2pcommunication && npm install
  - cd local_modules/p2pcommunication-client && npm install
before_script:
  - cd local_modules/p2pcommunication && npm run build
  - cd local_modules/p2pcommunication-client && npm run build
script:
  - cd local_modules/p2pcommunication && npm run test-server& cd ../p2pcommunication-client && npm test
